export enum ELocaleType {
  EN = 'en',
  NB = 'nb',
  NN = 'nn',
}

export enum ESanityMappe {
  FORSIDE = 'FORSIDE',
  SEND_ENDRINGER = 'SEND_ENDRINGER',
  KVITTERING = 'KVITTERING',
  FELLES = 'FELLES',
  DOKUMENTASJON = 'DOKUMENTASJON',
}

export enum ESteg {
  FORSIDE = 'FORSIDE',
  SEND_ENDRINGER = 'SEND_ENDRINGER',
  KVITTERING = 'KVITTERING',
  DOKUMENTASJON = 'DOKUMENTASJON',
}
