export enum ETypografiTyper {
  HEADING_H1 = 'HEADING_H1',
  STEG_HEADING_SMALL_H1 = 'STEG_HEADING_SMALL_H1',
  HEADING_H2 = 'HEADING_H2',
  BANNER_HEADING = 'BANNER_HEADING',
  BODY_SHORT = 'BODY_SHORT',
  LABEL = 'LABEL',
  SPAN = 'SPAN',
}
